#ifndef STACK_PADES_H
#define STACK_PADES_H

#include <openssl/safestack.h>

#define sk_VRI_new(cmp) SKM_sk_new(VRI, (cmp))
#define sk_VRI_new_null() SKM_sk_new_null(VRI)
#define sk_VRI_free(st) SKM_sk_free(VRI, (st))
#define sk_VRI_num(st) SKM_sk_num(VRI, (st))
#define sk_VRI_value(st, i) SKM_sk_value(VRI, (st), (i))
#define sk_VRI_set(st, i, val) SKM_sk_set(VRI, (st), (i), (val))
#define sk_VRI_zero(st) SKM_sk_zero(VRI, (st))
#define sk_VRI_push(st, val) SKM_sk_push(VRI, (st), (val))
#define sk_VRI_unshift(st, val) SKM_sk_unshift(VRI, (st), (val))
#define sk_VRI_find(st, val) SKM_sk_find(VRI, (st), (val))
#define sk_VRI_find_ex(st, val) SKM_sk_find_ex(VRI, (st), (val))
#define sk_VRI_delete(st, i) SKM_sk_delete(VRI, (st), (i))
#define sk_VRI_delete_ptr(st, ptr) SKM_sk_delete_ptr(VRI, (st), (ptr))
#define sk_VRI_insert(st, val, i) SKM_sk_insert(VRI, (st), (val), (i))
#define sk_VRI_set_cmp_func(st, cmp) SKM_sk_set_cmp_func(VRI, (st), (cmp))
#define sk_VRI_dup(st) SKM_sk_dup(VRI, st)
#define sk_VRI_pop_free(st, free_func) SKM_sk_pop_free(VRI, (st), (free_func))
#define sk_VRI_deep_copy(st, copy_func, free_func) SKM_sk_deep_copy(VRI, (st), (copy_func), (free_func))
#define sk_VRI_shift(st) SKM_sk_shift(VRI, (st))
#define sk_VRI_pop(st) SKM_sk_pop(VRI, (st))
#define sk_VRI_sort(st) SKM_sk_sort(VRI, (st))
#define sk_VRI_is_sorted(st) SKM_sk_is_sorted(VRI, (st))

#define sk_PolicyArtifact_new(cmp) SKM_sk_new(PolicyArtifact, (cmp))
#define sk_PolicyArtifact_new_null() SKM_sk_new_null(PolicyArtifact)
#define sk_PolicyArtifact_free(st) SKM_sk_free(PolicyArtifact, (st))
#define sk_PolicyArtifact_num(st) SKM_sk_num(PolicyArtifact, (st))
#define sk_PolicyArtifact_value(st, i) SKM_sk_value(PolicyArtifact, (st), (i))
#define sk_PolicyArtifact_set(st, i, val) SKM_sk_set(PolicyArtifact, (st), (i), (val))
#define sk_PolicyArtifact_zero(st) SKM_sk_zero(PolicyArtifact, (st))
#define sk_PolicyArtifact_push(st, val) SKM_sk_push(PolicyArtifact, (st), (val))
#define sk_PolicyArtifact_unshift(st, val) SKM_sk_unshift(PolicyArtifact, (st), (val))
#define sk_PolicyArtifact_find(st, val) SKM_sk_find(PolicyArtifact, (st), (val))
#define sk_PolicyArtifact_find_ex(st, val) SKM_sk_find_ex(PolicyArtifact, (st), (val))
#define sk_PolicyArtifact_delete(st, i) SKM_sk_delete(PolicyArtifact, (st), (i))
#define sk_PolicyArtifact_delete_ptr(st, ptr) SKM_sk_delete_ptr(PolicyArtifact, (st), (ptr))
#define sk_PolicyArtifact_insert(st, val, i) SKM_sk_insert(PolicyArtifact, (st), (val), (i))
#define sk_PolicyArtifact_set_cmp_func(st, cmp) SKM_sk_set_cmp_func(PolicyArtifact, (st), (cmp))
#define sk_PolicyArtifact_dup(st) SKM_sk_dup(PolicyArtifact, st)
#define sk_PolicyArtifact_pop_free(st, free_func) SKM_sk_pop_free(PolicyArtifact, (st), (free_func))
#define sk_PolicyArtifact_deep_copy(st, copy_func, free_func) SKM_sk_deep_copy(PolicyArtifact, (st), (copy_func), (free_func))
#define sk_PolicyArtifact_shift(st) SKM_sk_shift(PolicyArtifact, (st))
#define sk_PolicyArtifact_pop(st) SKM_sk_pop(PolicyArtifact, (st))
#define sk_PolicyArtifact_sort(st) SKM_sk_sort(PolicyArtifact, (st))
#define sk_PolicyArtifact_is_sorted(st) SKM_sk_is_sorted(PolicyArtifact, (st))

#define sk_LpaArtifact_new(cmp) SKM_sk_new(LpaArtifact, (cmp))
#define sk_LpaArtifact_new_null() SKM_sk_new_null(LpaArtifact)
#define sk_LpaArtifact_free(st) SKM_sk_free(LpaArtifact, (st))
#define sk_LpaArtifact_num(st) SKM_sk_num(LpaArtifact, (st))
#define sk_LpaArtifact_value(st, i) SKM_sk_value(LpaArtifact, (st), (i))
#define sk_LpaArtifact_set(st, i, val) SKM_sk_set(LpaArtifact, (st), (i), (val))
#define sk_LpaArtifact_zero(st) SKM_sk_zero(LpaArtifact, (st))
#define sk_LpaArtifact_push(st, val) SKM_sk_push(LpaArtifact, (st), (val))
#define sk_LpaArtifact_unshift(st, val) SKM_sk_unshift(LpaArtifact, (st), (val))
#define sk_LpaArtifact_find(st, val) SKM_sk_find(LpaArtifact, (st), (val))
#define sk_LpaArtifact_find_ex(st, val) SKM_sk_find_ex(LpaArtifact, (st), (val))
#define sk_LpaArtifact_delete(st, i) SKM_sk_delete(LpaArtifact, (st), (i))
#define sk_LpaArtifact_delete_ptr(st, ptr) SKM_sk_delete_ptr(LpaArtifact, (st), (ptr))
#define sk_LpaArtifact_insert(st, val, i) SKM_sk_insert(LpaArtifact, (st), (val), (i))
#define sk_LpaArtifact_set_cmp_func(st, cmp) SKM_sk_set_cmp_func(LpaArtifact, (st), (cmp))
#define sk_LpaArtifact_dup(st) SKM_sk_dup(LpaArtifact, st)
#define sk_LpaArtifact_pop_free(st, free_func) SKM_sk_pop_free(LpaArtifact, (st), (free_func))
#define sk_LpaArtifact_deep_copy(st, copy_func, free_func) SKM_sk_deep_copy(LpaArtifact, (st), (copy_func), (free_func))
#define sk_LpaArtifact_shift(st) SKM_sk_shift(LpaArtifact, (st))
#define sk_LpaArtifact_pop(st) SKM_sk_pop(LpaArtifact, (st))
#define sk_LpaArtifact_sort(st) SKM_sk_sort(LpaArtifact, (st))
#define sk_LpaArtifact_is_sorted(st) SKM_sk_is_sorted(LpaArtifact, (st))

#define sk_LpaSignature_new(cmp) SKM_sk_new(LpaSignature, (cmp))
#define sk_LpaSignature_new_null() SKM_sk_new_null(LPA)
#define sk_LpaSignature_free(st) SKM_sk_free(LpaSignature, (st))
#define sk_LpaSignature_num(st) SKM_sk_num(LpaSignature, (st))
#define sk_LpaSignature_value(st, i) SKM_sk_value(LpaSignature, (st), (i))
#define sk_LpaSignature_set(st, i, val) SKM_sk_set(LpaSignature, (st), (i), (val))
#define sk_LpaSignature_zero(st) SKM_sk_zero(LpaSignature, (st))
#define sk_LpaSignature_push(st, val) SKM_sk_push(LpaSignature, (st), (val))
#define sk_LpaSignature_unshift(st, val) SKM_sk_unshift(LpaSignature, (st), (val))
#define sk_LpaSignature_find(st, val) SKM_sk_find(LpaSignature, (st), (val))
#define sk_LpaSignature_find_ex(st, val) SKM_sk_find_ex(LpaSignature, (st), (val))
#define sk_LpaSignature_delete(st, i) SKM_sk_delete(LpaSignature, (st), (i))
#define sk_LpaSignature_delete_ptr(st, ptr) SKM_sk_delete_ptr(LpaSignature, (st), (ptr))
#define sk_LpaSignature_insert(st, val, i) SKM_sk_insert(LpaSignature, (st), (val), (i))
#define sk_LpaSignature_set_cmp_func(st, cmp) SKM_sk_set_cmp_func(LpaSignature, (st), (cmp))
#define sk_LpaSignature_dup(st) SKM_sk_dup(LpaSignature, st)
#define sk_LpaSignature_pop_free(st, free_func) SKM_sk_pop_free(LpaSignature, (st), (free_func))
#define sk_LpaSignature_deep_copy(st, copy_func, free_func) SKM_sk_deep_copy(LpaSignature, (st), (copy_func), (free_func))
#define sk_LpaSignature_shift(st) SKM_sk_shift(LpaSignature, (st))
#define sk_LpaSignature_pop(st) SKM_sk_pop(LpaSignature, (st))
#define sk_LpaSignature_sort(st) SKM_sk_sort(LpaSignature, (st))
#define sk_LpaSignature_is_sorted(st) SKM_sk_is_sorted(LpaSignature, (st))

#endif
